# Generated by Django 3.1.1 on 2020-09-14 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroDeInventario', models.CharField(max_length=200)),
                ('responsable', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('noSerie', models.CharField(max_length=200)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pc')),
            ],
        ),
        migrations.CreateModel(
            name='Teclado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('noSerie', models.CharField(max_length=200)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pc')),
            ],
        ),
        migrations.CreateModel(
            name='Targeta_de_Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('capacidad', models.CharField(max_length=200)),
                ('noSerie', models.CharField(max_length=200)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pc')),
            ],
        ),
        migrations.CreateModel(
            name='Targeta_de_Red',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('noSerie', models.CharField(max_length=200)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pc')),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('capacidad', models.CharField(max_length=200)),
                ('noSerie', models.CharField(max_length=200)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pc')),
            ],
        ),
        migrations.AddField(
            model_name='pc',
            name='SO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.so'),
        ),
        migrations.AddField(
            model_name='pc',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.area'),
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('noSerie', models.CharField(max_length=200)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pc')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('noSerie', models.CharField(max_length=200)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pc')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('noSerie', models.CharField(max_length=200)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pc')),
            ],
        ),
        migrations.CreateModel(
            name='Lector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('noSerie', models.CharField(max_length=200)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pc')),
            ],
        ),
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('capacidad', models.CharField(max_length=200)),
                ('noSerie', models.CharField(max_length=200)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pc')),
            ],
        ),
        migrations.CreateModel(
            name='Fuente_Interna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('capacidad', models.CharField(max_length=200)),
                ('noSerie', models.CharField(max_length=200)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pc')),
            ],
        ),
        migrations.CreateModel(
            name='Estabilizador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('noSerie', models.CharField(max_length=200)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pc')),
            ],
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('capacidad', models.CharField(max_length=200)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pc')),
            ],
        ),
        migrations.CreateModel(
            name='Bocinas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('noSerie', models.CharField(max_length=200)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pc')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.region'),
        ),
    ]
