# Generated by Django 3.1.1 on 2020-09-15 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='enRed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('noSerie', models.CharField(max_length=200)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.pc')),
            ],
        ),
    ]
