# Generated by Django 3.1.1 on 2020-09-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20200915_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresora',
            name='icono',
            field=models.CharField(default='no tiene', max_length=200),
        ),
    ]
